name: uniswipe
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  fonts:  
    - family: Modernist  
      fonts:
        - asset: assets/fonts/Modernist.otf
    - family: Pacifico  
      fonts:
        - asset: assets/fonts/Pacifico.ttf