// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVQWRXkkiWglilfWNE8NN4mT-VaeWE6wQ',
    appId: '1:241941247041:web:20e3146b7a4321cc8802c0',
    messagingSenderId: '241941247041',
    projectId: 'uniswipe-bb5ea',
    authDomain: 'uniswipe-bb5ea.firebaseapp.com',
    storageBucket: 'uniswipe-bb5ea.firebasestorage.app',
    measurementId: 'G-1P74J7NBN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuhOWGq_NX2JtRBFcMUGyB2Bnai_8JWWo',
    appId: '1:241941247041:android:ccab6d9cc226aea28802c0',
    messagingSenderId: '241941247041',
    projectId: 'uniswipe-bb5ea',
    storageBucket: 'uniswipe-bb5ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKWkQNcIpPBIUUanqg1AdZcCsjXKoxAo',
    appId: '1:241941247041:ios:96f674aa842a5d558802c0',
    messagingSenderId: '241941247041',
    projectId: 'uniswipe-bb5ea',
    storageBucket: 'uniswipe-bb5ea.firebasestorage.app',
    iosBundleId: 'com.example.uniswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKWkQNcIpPBIUUanqg1AdZcCsjXKoxAo',
    appId: '1:241941247041:ios:96f674aa842a5d558802c0',
    messagingSenderId: '241941247041',
    projectId: 'uniswipe-bb5ea',
    storageBucket: 'uniswipe-bb5ea.firebasestorage.app',
    iosBundleId: 'com.example.uniswipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVQWRXkkiWglilfWNE8NN4mT-VaeWE6wQ',
    appId: '1:241941247041:web:e75c726c07e401c58802c0',
    messagingSenderId: '241941247041',
    projectId: 'uniswipe-bb5ea',
    authDomain: 'uniswipe-bb5ea.firebaseapp.com',
    storageBucket: 'uniswipe-bb5ea.firebasestorage.app',
    measurementId: 'G-4CQ6N2FMC3',
  );
}
